// Sidebar is autogenerated from the existing root docs/ directory, ordered
// by each page's sidebar_position frontmatter. No manual entries.
module.exports = {
	docs: [{ type: 'autogenerated', dirName: '.' }],
};
