global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 10s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ "alertmanager:9093" ]

scrape_configs:
  - job_name: "cacherelay"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets: [ "cacherelay:8080" ]
        labels:
          application: "CacheRelay"
          environment: "production"

  - job_name: "redis"
    scrape_interval: 15s
    static_configs:
      - targets: [ "redis-exporter:9121" ]
        labels:
          application: "CacheRelay"
          component: "redis"
          tier: "accounting"

  - job_name: "redis-cache"
    scrape_interval: 15s
    static_configs:
      - targets: [ "redis-cache-exporter:9121" ]
        labels:
          application: "CacheRelay"
          component: "redis"
          tier: "cache"

  - job_name: "postgres"
    scrape_interval: 15s
    static_configs:
      - targets: [ "postgres-exporter:9187" ]
        labels:
          application: "CacheRelay"
          component: "postgres"

  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: [ "localhost:9090" ]
